version: "3.9"

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    restart: always

  kube-argo-express:
    build:
      context: ./src
    image: localhost:5000/kube-argo-express:latest
    environment:
      - API_VERSION=v1
    ports:
      - "8080:8080"
    depends_on:
      - registry
